services:
  - type: web
    name: flask-login-test
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    region: são paulo  # Puedes cambiar a 'frankfurt' si estás en Europa o 'são paulo' para Latinoamérica
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9